### ISSUE TITLE
iOS Crash on any BLE state change

### ISSUE THREAD

**Issue by jack4git** [Polidea/FlutterBleLib#14]
Happens instantly, in FlutterBleLib code.

[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.5 at /Users/jackivers/Projects/Flutter/flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jackivers/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.10.0

[✓] Connected devices (2 available)
    • SM J730GM    • 5200f375b274b4d9                         • android-arm • Android 7.0 (API 24) (emulator)
    • JSI iPhone X • 7abb1638e5f94117408869c9c5236c5acb0d7f0c • ios         • iOS 11.2.6

[Runner  3-21-18, 5-37 PM.crash.zip](https://github.com/Polidea/FlutterBleLib/files/1835506/Runner.3-21-18.5-37.PM.crash.zip)

**Comment by KKonradMC** [comment]
Thank you for reporting. Library is still in progress. We will take a look on it.

Regards
Konrad Krakowiak

**Comment by pawelByszewski** [comment]
@jack4git It has been a long time since we stopped maintaining the library but now we come with great news! We are currently working with Frontside on a new BLE Flutter library and BLE simulator. Beta version has been released already and we are going to release 2.0.0 in the first half of November
