### ISSUE TITLE
Question:  Advertisement Data?

### ISSUE THREAD

**Issue by TimBritton** [Polidea/FlutterBleLib#23]
Hello All!

Does this library have the ability to extract the advertisement data when a ble device has been detected?

I did not see it covered in the documentation anywhere.
Sorry if I messed it!
Best Regards,
Tim

**Comment by mikolak** [comment]
Hello @TimBritton!

This package hasn't been maintained for some time. It has gone through a complete rewrite since and now there's a different API and I hope you'll give it a chance!

In the new API the stream with results of the scan operation returns ScanResult containing AdvertisementData.
