### ISSUE TITLE
SimulatedPeripheral's id should be in the format of uuid instead of mac address for iOS

### ISSUE THREAD

**Issue by TomoLV** [Polidea/FlutterBleLib#230]
Currently in`lib/blemulator/example/example_peripheral.dart` SimulatedPeripheral's `id` (which is of String type) is being passed in the format of Mac Address which is not suitable for iOS (if we want to keep blemulator's simulated peripherals in line with real peripherals).

The solution would be to introduce some mechanism that is able to detect on what platform blemulator is being tested and adjust `id` value accordingly.

**Comment by NOA-Charles** [comment]
I think this is a function that developers have to complete by themselves, and plugins cannot provide this function. ^_^
