### ISSUE TITLE
Is it possible to receive BLE service notification while activity running in background?

### ISSUE THREAD

**Issue by alishir** [Polidea/FlutterBleLib#24]
Is it possible to receive BLE service notification in the activity that is running in background? I want to continuously monitor hear rate measurement while the user switching between different applications.

**Comment by kitolog** [comment]
Same here
I need to read characteristics updates running in background, iOS

**Comment by mikolak** [comment]
@alishir 
You may need to use foreground service to keep your application alive and avoid background work limit.

@kitolog 
[This link should help you](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html)

**Comment by Lootwig** [comment]
For anyone arriving through googling, https://github.com/Polidea/FlutterBleLib/issues/530#issuecomment-700412023 worked for me!
