### ISSUE TITLE
[FlutterBleLib] Monitored characteristics from `monitorCharacteristicForDevice()` are not filtered by `peripheralId`, which might cause multiple readings when monitoring characteristics with same service and characteristic UUID on different peripherals.

### ISSUE THREAD

**Issue by mikolak** [Polidea/FlutterBleLib#258]

**Comment by bartoszwilk** [comment]
Filtering by transactionId is enough for this case. 
However, starting monitoring on already used transactionId should emit error on old stream and should also close it, before returning new one. Current implementation won't work this way and I will create another issue for that.
In this task I will just add filtering events by transactionId which apparently was missed during the merge.
