### ISSUE TITLE
Write failed for Characteristic which has "is writable without response = true"

### ISSUE THREAD

**Issue by ssarangi** [Polidea/FlutterBleLib#30]
I have a characteristic which I can write to (using ios app LightBlue) but which fails the write with type string. Hex writes don't work because of issue #29 

Attached is the details from the service and characteristic. 

![attachment](https://user-images.githubusercontent.com/239816/41827990-770e06c6-77e7-11e8-9c9b-c28829c78afb.png)

**Comment by pawelByszewski** [comment]
@ssarangi It has been a long time since we stopped maintaining the library but now we come with great news! We are currently working with Frontside on a new BLE Flutter library and BLE simulator. Beta version has been released already and we are going to release 2.0.0 in the first half of November
