### ISSUE TITLE
Support for Descriptors

### ISSUE THREAD

**Issue by aytunch** [Polidea/FlutterBleLib#322]
For most of the BLE devices, we need to write/read/notify from their descriptors. As far as I checked, this library does not support this functionality. Is there any work around or plans to support descriptors?

**Comment by mikolak** [comment]
Hi!

There is no workaround, but there are definitely plans to support descriptor operations. I'm unable to give you any specific date, but it will happen rather sooner than later.

**Comment by JureLokovsek** [comment]
I used another ble lib for testing, it had the options to set notify to true, for example like this characteristic.setNotifyValue(true);
and then
characteristic.listen() ..... for values 
For this char uuid 00002a5e-0000-1000-8000-00805f9b34fb and it worked 
I am trying to do the same with this lib, but it seems that this is not possible for now or i dont know the right way doing it.  

I/flutter (27954):  Characteristics: 00002a5e-0000-1000-8000-00805f9b34fb
I/flutter (27954):  is Indicatable: true
I/flutter (27954):  is Notifiable: false
I/flutter (27954):  is Readable: false
I/flutter (27954):  is Writable With Response: false
I/flutter (27954):  is Writable Without Response: false

**Comment by mikolak** [comment]
Hi, @JureLokovsek.

If you want to get notifications/indications from a characteristic, call `characteristic.monitor().listen()`.

Here's an example: https://github.com/Polidea/FlutterBleLib/blob/master/example/lib/test_scenarios/peripheral_test_operations.dart#L207

I'd appreciate it, if you created a separate issue next time.

**Comment by mikolak** [comment]
BTW @aytunch I'm currently working on support for reading from/writing to descriptors. Should be out somewhere in January/early February for both FlutterBleLib and BLEmulator.

**Comment by JureLokovsek** [comment]
Hi, @mikolak 
Thank you for your answer, the suggestion you gave worked fine for me.
I am doing some researching and testing on flutter with some bluetooth devices, next time I will open seperate issue. Tnx again.

**Comment by aytunch** [comment]
@mikolak I am very glad to hear this. Hopefully after the descriptor support, I will be able to finish up my miband3 project:D

**Comment by mikolak** [comment]
@aytunch Descriptors have just been released in 2.2.0.

**Comment by aytunch** [comment]
> @aytunch Descriptors have just been released in 2.2.0.

@mikolak Just a small reminder. the Todo does not reflect the descriptor support. thanks btw.

**Comment by mikolak** [comment]
@aytunch What do you mean? What Todo?

**Comment by aytunch** [comment]
@mikolak I am sorry, I was talking about readme:

https://github.com/Polidea/FlutterBleLib/blob/develop/README.md

**Comment by mikolak** [comment]
Ah, sorry! Forgot about it! Thank you for letting me know, fixing it right away!
