### ISSUE TITLE
How to use Bluetooth low energy MESH on flutter (android/ios)

### ISSUE THREAD

**Issue by srimathselva** [Polidea/FlutterBleLib#35]
Dear All,
     I’m looking for Blue-tooth low energy MESH source code on flutter for Android/IOS. but I’m not getting the flutter source code . please someone help me on this.

**Questions :-  
1. Blue-tooth low energy MESH Source code available in flutter ?
2. It is possible to do Blue-tooth low energy MESH on flutter ?**

Thanks

**Comment by mikolak** [comment]
Hello,

This plugin doesn't provide MESH support. You can try creating your own using Nordic Semiconductor's libraries for native backend:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library

Regarding the second question - if it's possible on both iOS and Android (and it is, as there are libraries for it), then it's possible to achieve in Flutter.
