### ISSUE TITLE
about indicate 

### ISSUE THREAD

**Issue by spd-heshuip** [Polidea/FlutterBleLib#358]
i use this library to receive the packet by other bluetooth device indicate ,but sometimes it will lost some packet;

**Comment by mikolak** [comment]
Hi!

Sorry, but you'll need to be more clear. Is it a random indication that gets lost or right at the start of subscription? How do you know that it gets lost, are you sniffing communication? Does it happen on both platforms?

**Comment by spd-heshuip** [comment]
it is get lost right at the start of subscription.i did not  sniffing communication.and i know that it gets lost because i had check the packet which  send by the bluetooth devices; the bluetooth devices show has indicate success on the log,  but the phone lost one of the packet; for the moment  i  just  test it on the android ;

**Comment by mikolak** [comment]
Version 2.1.0 with fix has just been released.
