### ISSUE TITLE
Value conversions

### ISSUE THREAD

**Issue by JureLokovsek** [Polidea/FlutterBleLib#359]
Hi,
I am using RxAndroidBle in my android app, but now I am trying to write the same app in Flutter.
This is the Service characteristic that I am monitoring: 00001822-0000-1000-8000-00805f9b34fb 
and the characteristic: 00002a5e-0000-1000-8000-00805f9b34fb.

Here is the byte data from RxAndroidBle: [31, -54, -13, 71, 0, -32, 7, 1, 7, 4, 41, 2, 0, 1, 1, 0, 0, -121, -25]
Here is the Uint8List data from FlutterBleLib: [31, 212, 243, 57, 0, 224, 7, 1, 6, 5, 9, 21, 0, 1, 0, 0, 0, 91, 228]

The RxAndroidBle lib has ValueInterpreter to convert byte data to int.
For example in Java: 
int offset = 0;
final int flags = ValueInterpreter.getIntValue(value, FORMAT_UINT8, offset);
The value here is the first array above.

Does FlutterBleLib have ValueInterpreter? if not how can I then convert these values? I need a starting point from which I can work from :)

**Comment by mikolak** [comment]
Hi!

The library does not provide any interpreter at the moment, we might add it in future. 

For now you could try this approach: https://stackoverflow.com/questions/31688061/how-do-i-read-a-16-bit-int-from-a-uint8list-in-dart
