### ISSUE TITLE
Programmatically bonding to BLE device

### ISSUE THREAD

**Issue by JureLokovsek** [Polidea/FlutterBleLib#360]
Hi,
On Android using the RxAndroidBle lib, we have the option to create a bond via code.
For example: bluetoothDevice.createBond();
I checked trough the ble lib code and didn't found a similar method.
Is there a way to do this at this moment with the lib or will it be supported later?

**Comment by mikolak** [comment]
Hi!

This library uses the same backend as react-native-ble-plx, so the following answer applies here as well:
https://github.com/Polidea/react-native-ble-plx/wiki/Device-Bonding
