### ISSUE TITLE
[iOS] Crash in observeBluetoothState method

### ISSUE THREAD

**Issue by rmorbach** [Polidea/FlutterBleLib#367]
Using the following code will result in a crash on iOS as soon as the Bluetooth Adapter status changes:

```dart
BleManager bleManager =  BleManager();
await bleManager.createClient();
bleManager.observeBluetoothState().listen((newState) {
    //...
});
```

This will throw the following exception in Xcode: 
```ObjC
-[__NSCFString objectAtIndexedSubscript:]: unrecognized selector sent to instance
```
Using debug breakpoints in Xcode, it seems the error is thrown in the line 25 of the the method: `- (void)onNewAdapterState:(NSArray *)bluetoothAdapterState` of `AdapterStateStreamHandler.m` file.

![Screen Shot 2020-01-07 at 16 10 02](https://user-images.githubusercontent.com/4155485/71925240-5ecf5b80-316f-11ea-8ed9-b96962316f11.png)

It looks like you are passing a `NSString` instance while the method expects a `NSArray`. This method is called in the `FlutterBleLib.m` file.

![Screen Shot 2020-01-07 at 16 10 25](https://user-images.githubusercontent.com/4155485/71925253-62fb7900-316f-11ea-90c2-c90b01dcbb55.png)

The specific method is:
![Screen Shot 2020-01-07 at 16 43 11](https://user-images.githubusercontent.com/4155485/71925204-4fe8a900-316f-11ea-92c6-b6044a3b4540.png)

**Comment by mikolak** [comment]
Hi @rmorbach !

Thanks for the ticket and the investigation! I'll try to fix it and release new patch version this week.

**Comment by mikolak** [comment]
Version 2.1.0 with fix has just been released.
