### ISSUE TITLE
Support for AndroidX.

### ISSUE THREAD

**Issue by mikolak** [Polidea/FlutterBleLib#396]

**Comment by KevinRohn** [comment]
Is AndroidX already supported?

**Comment by mikolak** [comment]
@KevinRohn Jetifier should handle it for now. We haven't yet swapped Support for AndroidX in the library.

**Comment by KevinRohn** [comment]
@mikolak What does this exactly mean? I've built the example project and run it on my Huawei Mate 20 Pro with AndroidX - There is the same issue like on all other current Flutter BLE packages, that the scan result always seems to be empty. For iOS and < AndroidX it works fine

**Comment by mikolak** [comment]
I'm not sure if your issue connected to AndroidX, especially since we only use Not Null annotations in the library code IIRC. Are you granting location permission to the example? Can you set log level to verbose and check the logs after scanning for peripherals?
