### ISSUE TITLE
Support for multiple platforms, such as web, macOS, Windows, Linux, etc.

### ISSUE THREAD

**Issue by mikolak** [Polidea/FlutterBleLib#403]
Research task. Are other platforms compatible with this API, expected workload per platform, is it something that Polidea would like to invest in?

**Comment by TimWhiting** [comment]
It looks like RxBluetoothKit is compatible with MacOS. How hard would it be to support MacOS? I'm guessing you wouldn't need to change much from the iOS implementation, and could possibly just use the iOS implementation?
