### ISSUE TITLE
BLE Plugin does not need to have the ability to apply for permissions

### ISSUE THREAD

**Issue by NOA-Charles** [Polidea/FlutterBleLib#422]
"permission_handler" is used in the plugin, I don't think it is good, because "permission_handler" will lead to the need to add extra Purchase String in Info.plist.

Would you consider giving up the ability to gain permissions in this plugin?

**Comment by mikolak** [comment]
It got into wrong pubspec by mistake, it should be in example. I'll release a patch version today fixing this.
