### ISSUE TITLE
[Question] Maintain connection when device is locked

### ISSUE THREAD

**Issue by tdnghia98** [Polidea/FlutterBleLib#438]
Hi,
Is it possible to maintain the connection and send data when the telephone is locked? I'd like to use the lib with a connected bike via bluetooth and I need to have data transmitted when the user locked their phone
Thanks.

**Comment by mikolak** [comment]
Hi!

I suppose you could launch the plugin from [foreground service ](https://developer.android.com/guide/components/services) on Android. I don't know what's the situation on iOS, but perhaps you'd be able to use background mode ([example article](https://medium.com/arkulpa/ios-stay-connected-to-an-external-ble-device-as-much-as-possible-699d434846d2))?
