### ISSUE TITLE
[Question] Pairing and Bonding

### ISSUE THREAD

**Issue by tdnghia98** [Polidea/FlutterBleLib#446]
Hello,
Is it possible to do pairing and bonding with this library? If there are services that I don't want to expose to public, how can I do to 'authorize' my application? I know that natively there will be a pairing pop up that appears, but it does not seem to be implemented.

**Comment by dariuszseweryn** [comment]
Pairing is handled by the OS and the app/library has nothing to do with it apart from retrying requests if needed
