### ISSUE TITLE
[Question] Connecting two phones - enabling a phone as a peripheral.

### ISSUE THREAD

**Issue by sashajo** [Polidea/FlutterBleLib#448]
Hello,
I've noticed that underlaying library supports turning a phone into peripheral but I didn't see that option in this flutter plugin. Are there plans to extend plugin to allow connectivity between 2 phones and exchange of data?
Many thanks

**Comment by mikolak** [comment]
I think underlying libraries do not support it, but it's certainly something we're thinking of. Unfortunately it's a rather low priority and a big workload, so I don't think it will happen in near future.

**Comment by tonypottera24** [comment]
+1 for the peripheral and GATT server functionality.
