### ISSUE TITLE
Can not work on iPad and iPhone

### ISSUE THREAD

**Issue by hu70258tao** [Polidea/FlutterBleLib#450]
both system is 13.4，
iPad sometime can not read and write，and tall bleerro code 205,means disconnect，but I try check bledevice,it still connected。
iPhone can not scan any bledevice，and always BluetoothState.UNKNOWN 。

**Comment by mikolak** [comment]
Hi!

Have you followed the installation guide? https://github.com/Polidea/FlutterBleLib#ios
Can you run the sample the from the library and see if you encounter the same issues?

**Comment by hu70258tao** [comment]
my English is very weak，I test as soon as posible

**Comment by hu70258tao** [comment]
it can run on iPad,but throw erro on iPhone,
![image](https://user-images.githubusercontent.com/20218008/78110753-1eaa0d00-742e-11ea-9cfb-cdd50c3a29e5.png)

**Comment by hu70258tao** [comment]
and this project is your example

**Comment by hu70258tao** [comment]
![image](https://user-images.githubusercontent.com/20218008/78112335-abee6100-7430-11ea-9d17-80f2fa0ef009.png)
Ipad can scan BleDevice,but iPhone can not

**Comment by hu70258tao** [comment]
And I user a iOS App called LightBlue,it can scan many device
![image](https://user-images.githubusercontent.com/20218008/78112986-9af21f80-7431-11ea-9074-68ef7f9d5e74.png)

**Comment by hu70258tao** [comment]
I test iPhone8 system is 13.4，Iphone7 system 13.31,both not work,
and I test IphoneX just now,it is work,and system is 13.3.1

**Comment by hu70258tao** [comment]
![image](https://user-images.githubusercontent.com/20218008/78115516-7c8e2300-7435-11ea-8495-4bbe5ac2d980.png)
and when I write anything,it return erro coed 205 like this.i finad it is mean device disconnect,but my bluedevice received message and it is still connected.

**Comment by john-yick** [comment]
@hu70258tao It should work fine, I am testing on an iPhone X on ios 13.4 with running flutter stable version.

**Comment by mikolak** [comment]
I have no idea about iPad and currently have no means to test it, but the example filters out peripherals without a name.

https://github.com/Polidea/FlutterBleLib/blob/79ebf4423969dedaca3cca0b9220504d121aab80/example/lib/devices_list/devices_bloc.dart#L113

Change the condition in _startScan() to:

```
void _startScan() {
    Fimber.d("Ble client created");
    _scanSubscription =
        _bleManager.startPeripheralScan().listen((ScanResult scanResult) {
      var bleDevice = BleDevice(scanResult);
      if (!bleDevices.contains(bleDevice)) {
        Fimber.d(
            'found new device ${scanResult.advertisementData.localName} ${scanResult.peripheral.identifier}');
        bleDevices.add(bleDevice);
        _visibleDevicesController.add(bleDevices.sublist(0));
      }
    });
  }
```
And it should find your unnamed peripherals.

I'll change the example to stop omitting those.

**Comment by hu70258tao** [comment]
thanks very much,i will try and test

**Comment by hu70258tao** [comment]
and I write ,it always err like this
![image](https://user-images.githubusercontent.com/20218008/79196465-bfeb8700-7e62-11ea-8920-dc405df336ef.png)

**Comment by mikolak** [comment]
It'd seem you're trying to write an unsupported value.
https://stackoverflow.com/a/63341036
