### ISSUE TITLE
How can I get ManufacturerSpecificData

### ISSUE THREAD

**Issue by SupotSaeEa** [Polidea/FlutterBleLib#47]
Console shown list of onScanResult();
How can I get mManufacturerSpecificData ?

D/BluetoothLeScanner(31044): onScanResult() - ScanResult{mDevice=3D:14:34:32:FC:E7, mScanRecord=ScanRecord [mAdvertiseFlags=-1, mServiceUuids=null, mManufacturerSpecificData={6=[1, 9, 32, 2, -108, -121, -70, 22, 81, 7, 57, -88, 73, -77, -42, 3, -96, 85, 53, -89, -83, 114, -128, 15, -123, -61, 121]}, mServiceData={}, mTxPowerLevel=-2147483648, mDeviceName=null], mRssi=-41, mTimestampNanos=2112780591420409}

**Comment by mikolak** [comment]
Hi! I'm sorry for the long radio silence. Library has not been maintained in a long time, but it's back now with new API.

In the new version, you can access manufacturer specific data straight from the ScanResult: `scanResult.advertisementData.manufacturerData`.
