### ISSUE TITLE
[iOS] Connect to device doesn't seem to respect timeout

### ISSUE THREAD

**Issue by cbreezier** [Polidea/FlutterBleLib#478]
```
      try {
        await device.connect(timeout: Duration(seconds: 3));
      } catch (e) {
        debugPrint('Failed to connect to device: $e');
        Util.showError(context, 'Failed to connect to device');

        return await onError.call(device, e);
      }
```

`device` is a `Peripheral` object. This dart code works fine on Android, where a connection attempt is cancelled after 3 seconds and an exception is thrown (and caught).

However, the same code doesn't seem to do anything on iOS. The connection attempt seems to last forever.

Is the `timeout` parameter supported on iOS?

**Comment by mikolak** [comment]
It should work the same way.
https://github.com/Polidea/MultiPlatformBleAdapter/blob/master/iOS/classes/BleModule.swift#L400

**Comment by dokinkon** [comment]
Same issue with version 2.2.6

**Comment by jaromeyer** [comment]
i have the same issue

**Comment by jaromeyer** [comment]
As a workaround you can use flutters timeout method:
`await device.connect().timeout(Duration(seconds: 10));`

If you have some issues with scanning or connecting to the device once it's available/in range again, also add this hack:
```
try {
   await device.disconnectOrCancelConnection();
} catch (e) {}
```

**Comment by HerrNiklasRaab** [comment]
@mikolak Any upates?

**Comment by mikolak** [comment]
No news, sorry. I'll try to fix it this month.

**Comment by mikolak** [comment]
Almost a half year later, but the issue will be fixed in the nearest release, probably by the end of the week.
