### ISSUE TITLE
There is any way to check the scan state ？

### ISSUE THREAD

**Issue by philos3** [Polidea/FlutterBleLib#481]
There is any way to check the scan state like :

//    if (_scanStateSub == null) {
//      _scanStateSub = FlutterBlue.instance.isScanning.listen((result) {
//        print("_scanStateSub isScanning：====================================$result");
//        if(mounted){
//          setState(() {
//            isScanning = result;
//          });
//        }
//        if(result){
//          Future.delayed(Duration.zero, () {
//            showLoadingDialog(myContext, "正在连接设备",true);
//          });
//        }
//      });
//    }

**Comment by mikolak** [comment]
No. You can wrap subscribing to `startScan()` in a function that would switch your internal flag.

**Comment by philos3** [comment]
> No. You can wrap subscribing to `startScan()` in a function that would switch your internal flag.

thanks for help
