### ISSUE TITLE
VIE AL10 • 8FS5T16906007381 • android-arm64 • Android 8.0.0 (API 26)  startDeviceScan  error

### ISSUE THREAD

**Issue by philos3** [Polidea/FlutterBleLib#488]
D/com.polidea.flutter_ble_lib.FlutterBleLibPlugin(19761): on native side observed method: startDeviceScan
I/flutter (19761): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter (19761): The following BleError object was thrown:
I/flutter (19761):   BleError (Error code: 601, ATT error code: null, iOS error code: null, Android error code: null,
I/flutter (19761): reason: Location Services disabled (code 4), internal message: null, device ID: null, service UUID:
I/flutter (19761): null, characteristic UUID: null, descriptor UUID: null)
I/flutter (19761): 
I/flutter (19761): When the exception was thrown, this was the stack:
I/flutter (19761): #0      ScanningMixin.startDeviceScan.<anonymous closure> (package:flutter_ble_lib/src/bridge/scanning_mixin.dart:33:9)
I/flutter (19761): (elided 21 frames from dart:async)
I/flutter (19761): ...
I/flutter (19761): ════════════════════════════════════════════════════════════════════════════════════════════════════

[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900], locale zh-CN)
    • Flutter version 1.17.3 at C:\flutter\flutter
    • Framework revision b041144f83 (4 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Users\Administrator\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\Administrator\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6392135\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Users\Administrator\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6392135
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • VIE AL10 • 8FS5T16906007381 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

**Comment by mikolak** [comment]
> I/flutter (19761): reason: Location Services disabled (code 4), internal message: null, device ID: null, service UUID:
You either have disabled location or no Permission.ACCESS_COARSE_LOCATION.
