### ISSUE TITLE
Negotiated MTU is not honored

### ISSUE THREAD

**Issue by albrownwood** [Polidea/FlutterBleLib#508]
client: samsung G930F, Android7
peripheral: rpi zero w , Bluez

MTU negotiated at 128Bytes, write 128 Bytes to characteristic, 125 Bytes are actually received on peripheral (end of buffer truncated)
MTU negotiated at 255Bytes, write 255 Bytes to characteristic, 252 Bytes are actually received on peripheral (end of buffer truncated)

Not sure if the issue is from client or peripheral side.

**Comment by Bobby9292** [comment]
I thinks it's due to the 3 bytes required for the ATT header. It's better to negotiate 3 bytes larger than the size of your write data. 
Hope it helps.
