### ISSUE TITLE
Natenczas Wojski

### ISSUE THREAD

**Issue by JasonEdinburgh** [Polidea/FlutterBleLib#527]
When I use NRFconnect I see that the server has these fields

![image](https://user-images.githubusercontent.com/5156571/93436206-c2975000-f8ca-11ea-89d6-08446ca1e290.png)

First Name "Natenczas"
Last Name "Wojski"

He seems to be one of the characters in Adam Mickiewicz's epic Pan Tadeusz . 

**Is there any way for me to change these fields?**

**Comment by mikolak** [comment]
Hi!

Our library handles the `client` tab from nRF Connect. Are you sure you've posted this in the right place? 🙂 

I don't know what peripheral you're using, but I'm guessing that since someone set them, you could that as well.

**Comment by JasonEdinburgh** [comment]
Sorry if I didn't make myself clear. The device was connected to my flutter app with FlutterBleLib. I assumed that this is why the values were shown in the server tab.

**Comment by JasonEdinburgh** [comment]
you are right..... this is not related to FlutterBleLib. I see this without connecting with my phone..

How strange! Sorry for wasting your time

**Comment by Xprogrammer777** [comment]
Location: chest.. etc... look like linux sarcastic humor I don't understand... It is i a joke from RFconnect?
