### ISSUE TITLE
non-SDK interface error when reading and writing

### ISSUE THREAD

**Issue by joshting** [Polidea/FlutterBleLib#533]
I hope this is something not related to the library but some thing I can configure to make it go away.  I narrow down the problem to each time I perform read or write to a charateristic.

In the android app build.gradle: minSdkVersion is 19 and targetSdkVersion is 28

Accessing hidden method Lsun/misc/Unsafe;->getObjectVolatile(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
Accessing hidden method Lsun/misc/Unsafe;->putOrderedObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
Accessing hidden method Lsun/misc/Unsafe;->getLongVolatile(Ljava/lang/Object;J)J (greylist, linking, allowed)

**Comment by mikolak** [comment]
Wait, so what's the error? These are warnings, underlying native code has to be ported to newer API, but everything should be working fine at the moment.

**Comment by mikolak** [comment]
Duplicates #515
