### ISSUE TITLE
[question] Enable ble progrmatically in flutter 

### ISSUE THREAD

**Issue by redhotsixbull** [Polidea/FlutterBleLib#539]
Hi Thx u for u r package.

I have a question about ble. I am already suceess to connect with target device and reciveMsg and sendmsg.

but I can't find that How activate bluetooth Enable/disable in programtically.

**Comment by mikolak** [comment]
`bleManager.enableRadio()`
Keep in mind it only works on Android, iOS doesn't allow developers to manipulate BT's state.
