### ISSUE TITLE
Automatically reconnect on Gatt status 19

### ISSUE THREAD

**Issue by stastm12** [Polidea/FlutterBleLib#573]
I'm currently trying to implement a BLE Handling for a Flutter App to handle communication with some IoT Devices.

The Gatt Server of those Devices automatically sends status 19 (Connection closed by peripheral) after a few seconds

Now I ran into some issues with that because if I disconnect and reconnect using the library, the data on services and characteristics gets lost, but there is not enough time to discover the characteristics, set up a monitor for the characteristic I get an indication for and write data to the characteristic.

So I am wondering if there is any possibility to not have to go through the whole process and instead store the data across multiple connects/disconnects.

Thank you

**Comment by mikolak** [comment]
Adding a response for future generations: discovery is a system requirement upon establishing a connection, it has to always be done after connection.
