### ISSUE TITLE
Adding options to show Bluetooth power alert (when bluetooth is power off from control panel)

### ISSUE THREAD

**Issue by miguel-hyve** [Polidea/FlutterBleLib#576]
I have a requirement on an app and need to differentiate between 3 states:
- Bluetooth power off
- Bluetooth unauthorized for the app
- Bluetooth power off from control panel (Really, it's not power off but iOS not admitting new connections)

I have not found the way to handling the third state with the current code, but adding the option `CBCentralManagerOptionShowPowerAlertKey` on BluetoothManager constructor, the alert it's shown at the beginning

Are you thinking to add this option?

Thanks a lot!

![image](https://user-images.githubusercontent.com/79088019/109641644-3c0dbc80-7b52-11eb-98bc-537b017864ca.png)

![IMG_D1A4689FB9BA-1](https://user-images.githubusercontent.com/79088019/109642036-c81fe400-7b52-11eb-8896-43e47c6f4399.jpeg)

**Comment by mikolak** [comment]
`CBCentralManagerOptionShowPowerAlertKey` is responsible for showing automatic system alert to the user that they have Bluetooth turned off _when creating the BLE manager_. Unless you're destroying the client then and trying to recreate it every x seconds, I imagine you'd be better off implementing an alert dialog showing the user how to reenable BT and monitoring the state of the adapter, as the user will not be warned if they turned BT off after the manager was created.

This might also be an undesired behaviour, so it'd require quite a lot of API work to let the developer tell whether they'd like it or not. 

Perhaps if it gets enough traction in the future? Not really considering it now, as it seems as a really low priority.
