### ISSUE TITLE
peripheral.discoverAllServicesAndCharacteristics() finds cached (outdated) services

### ISSUE THREAD

**Issue by Simpler1** [Polidea/FlutterBleLib#593]
I'm building a BLE server and as I add or remove services, they are not found through the `peripheral.discoverAllServicesAndCharacteristics()` and `peripheral.services()` commands.

Other Bluetooth scanners such as _nRF Connect_ and _LightBlue_ both find the changed (added/removed) services, but _FlutterBleLib_ does not.

I've tried this with both 2.3.2 and 3.0.0-beta and both have the same issue.
I've tried flutter clean.
Uninstalled the flutter app and reinstalled through debug.
I even tried the example app from FlutterBleLib, but it also shows the old services (some of which don't even exist on the server any more).

Is there some other way to clear the cache and have it actually read the services again?

**Comment by Simpler1** [comment]
Using the big hammer method of resetting to factory defaults on the phone allowed it to find the updated services, but there must be a simpler way.

**Comment by mikolak** [comment]
Android or iOS?

**Comment by jobfeikens** [comment]
`peripheral.connect(refreshGatt: true)` (Android only)

**Comment by Simpler1** [comment]
Thanks guys...
Platform is Android.  I'll try the `refreshGatt: true`.

**Comment by Simpler1** [comment]
Problem resolved.
