### ISSUE TITLE
typo in doc

### ISSUE THREAD

**Issue by emdete** [Polidea/FlutterBleLib#9]
```
import 'package:flutter_ble_lib_example/ui/ble_devieces_screen.dart';
```

from (https://pub.dartlang.org/packages/flutter_ble_lib#-example-tab-) seems to be a typo and should read "devices", correct?

**Comment by KKonradMC** [comment]
Thank you for your suggestion. It's done but we have to wait for new version to see changes in https://pub.dartlang.org/packages/flutter_ble_lib#-example-tab-
